import type { CaregiverDemoBundle } from "./types";

export const CAREGIVER_DEMO: CaregiverDemoBundle = {
  caregiverName: "Priya",
  family: [
    {
      id: "ramesh",
      name: "Ramesh Patel",
      relationship: "Father",
      shortLabel: "Father",
      age: 68,
      avatarEmoji: "👨",
      recoveryScore: 82,
      status: "stable",
      statusLabel: "Stable",
      todayProgress: 78,
      vitals: [
        { label: "Medicine", status: "ok" },
        { label: "BP", status: "ok" },
        { label: "Sugar", status: "pending" },
      ],
      medicineAdherence: 94,
      trend: "improving",
      trendLabel: "Improving",
      nextAppointment: "Tomorrow",
      bloodGroup: "O+",
      allergies: ["None recorded"],
      emergencyContact: {
        name: "Priya Patel",
        phone: "+91 98765 88888",
        relationship: "Daughter",
      },
      doctorName: "Dr. Mehta",
      hospital: "Civil Hospital Ahmedabad",
      conditionSummary: "Post-discharge recovery after angioplasty",
      pmjayStatus: "Active · Covered",
      abhaId: "12-3456-7890-1101",
    },
    {
      id: "sita",
      name: "Sita Patel",
      relationship: "Mother",
      shortLabel: "Mother",
      age: 64,
      avatarEmoji: "👵",
      recoveryScore: 67,
      status: "needs_attention",
      statusLabel: "Needs Attention",
      todayProgress: 52,
      vitals: [
        { label: "Medicine", status: "alert" },
        { label: "Sugar", status: "alert" },
        { label: "BP", status: "ok" },
      ],
      medicineAdherence: 71,
      trend: "declining",
      trendLabel: "Needs care",
      nextAppointment: "Today 4:30 PM",
      bloodGroup: "B+",
      allergies: ["Penicillin"],
      emergencyContact: {
        name: "Priya Patel",
        phone: "+91 98765 88888",
        relationship: "Daughter",
      },
      doctorName: "Dr. Mehta",
      hospital: "Civil Hospital Ahmedabad",
      conditionSummary: "Type 2 diabetes · Hypertension post-discharge",
      pmjayStatus: "Active · Covered",
      abhaId: "12-3456-7890-1102",
    },
  ],
  timeline: {
    ramesh: [
      {
        id: "t1",
        time: "8:00 AM",
        title: "Morning Medicine",
        detail: "Aspirin 75 mg · Atorvastatin 20 mg taken",
        state: "done",
      },
      {
        id: "t2",
        time: "9:00 AM",
        title: "BP Recorded",
        detail: "128/82 mmHg — within target range",
        state: "done",
      },
      {
        id: "t3",
        time: "11:00 AM",
        title: "Sugar Reading Pending",
        detail: "Pre-lunch glucose check still open",
        state: "warning",
      },
      {
        id: "t4",
        time: "2:00 PM",
        title: "Walk Reminder",
        detail: "15-minute gentle walk after lunch",
        state: "upcoming",
      },
      {
        id: "t5",
        time: "6:00 PM",
        title: "Evening Medicine",
        detail: "Clopidogrel 75 mg with food",
        state: "upcoming",
      },
      {
        id: "t6",
        time: "8:00 PM",
        title: "Sleep Reminder",
        detail: "Aim for lights out by 10 PM",
        state: "upcoming",
      },
    ],
    sita: [
      {
        id: "s1",
        time: "7:30 AM",
        title: "Morning Medicine",
        detail: "Metformin dose was missed",
        state: "warning",
      },
      {
        id: "s2",
        time: "8:30 AM",
        title: "BP Recorded",
        detail: "134/86 mmHg — mildly elevated, monitoring",
        state: "done",
      },
      {
        id: "s3",
        time: "10:00 AM",
        title: "Sugar Reading",
        detail: "178 mg/dL — above target before snack",
        state: "warning",
      },
      {
        id: "s4",
        time: "1:00 PM",
        title: "Hydration Check",
        detail: "Only 2 glasses so far — encourage water",
        state: "pending",
      },
      {
        id: "s5",
        time: "4:30 PM",
        title: "Doctor Follow-up",
        detail: "Clinic visit with Dr. Mehta",
        state: "upcoming",
      },
      {
        id: "s6",
        time: "8:00 PM",
        title: "Evening Medicine",
        detail: "Amlodipine 5 mg · Metformin 500 mg",
        state: "upcoming",
      },
    ],
  },
  insights: {
    ramesh: [
      {
        id: "i1",
        title: "Recovery improved by 7% this week",
        why: "Daily walks and on-time medicines lifted his recovery score from 75 to 82.",
        tone: "positive",
      },
      {
        id: "i2",
        title: "Blood pressure remained stable",
        why: "Morning readings stayed between 122–132 systolic for five straight days.",
        tone: "positive",
      },
      {
        id: "i3",
        title: "Medicine adherence is excellent",
        why: "94% of scheduled doses were marked taken this week — keep the same routine.",
        tone: "positive",
      },
      {
        id: "i4",
        title: "Afternoon sugar check is still open",
        why: "Logging pre-lunch glucose helps the doctor spot patterns early.",
        tone: "attention",
      },
    ],
    sita: [
      {
        id: "si1",
        title: "Blood sugar needs attention",
        why: "Today's reading of 178 mg/dL is above her 140 target before meals.",
        tone: "attention",
      },
      {
        id: "si2",
        title: "Evening medicine was missed yesterday",
        why: "Missed Metformin doses raise next-day glucose — set a 8 PM reminder.",
        tone: "attention",
      },
      {
        id: "si3",
        title: "BP is mostly controlled",
        why: "Recent readings are close to target; continue low-salt meals.",
        tone: "neutral",
      },
      {
        id: "si4",
        title: "Hydration is below target",
        why: "Less than half of her 8-glass goal so far today.",
        tone: "attention",
      },
    ],
  },
  doctorMessages: {
    ramesh: [
      {
        id: "dm1",
        doctorName: "Dr. Ananya Mehta",
        specialty: "Cardiology",
        sentAt: "Today · 9:42 AM",
        paragraphs: [
          "Recovery is progressing well after discharge.",
          "Continue monitoring sugar before dinner and keep walking 15 minutes daily.",
          "Appointment remains scheduled for Tuesday at Civil Hospital.",
        ],
      },
    ],
    sita: [
      {
        id: "dm2",
        doctorName: "Dr. Ananya Mehta",
        specialty: "Internal Medicine",
        sentAt: "Today · 8:15 AM",
        paragraphs: [
          "Please watch Sita's afternoon sugar closely today.",
          "If readings stay above 180 after dinner, call the clinic before night.",
          "We'll review her Metformin timing at today's 4:30 PM visit.",
        ],
      },
    ],
  },
  alerts: {
    ramesh: [
      {
        id: "a1",
        priority: "medium",
        title: "Sugar reading pending",
        detail: "Pre-lunch glucose check is still open for Ramesh.",
        timeAgo: "12 min ago",
        actionLabel: "Remind him",
      },
      {
        id: "a2",
        priority: "low",
        title: "Appointment tomorrow",
        detail: "Cardiology follow-up at Civil Hospital, 10:30 AM.",
        timeAgo: "1 hr ago",
      },
      {
        id: "a3",
        priority: "low",
        title: "Water intake below target",
        detail: "4 of 8 glasses logged so far — a gentle nudge helps.",
        timeAgo: "2 hr ago",
      },
    ],
    sita: [
      {
        id: "sa1",
        priority: "critical",
        title: "Evening medicine missed",
        detail: "Metformin was not marked taken yesterday evening.",
        timeAgo: "Last night",
        actionLabel: "Mark plan",
      },
      {
        id: "sa2",
        priority: "high",
        title: "Blood sugar increased",
        detail: "Morning reading 178 mg/dL — above her care-plan target.",
        timeAgo: "40 min ago",
        actionLabel: "Call doctor",
      },
      {
        id: "sa3",
        priority: "medium",
        title: "Appointment today",
        detail: "Clinic visit with Dr. Mehta at 4:30 PM.",
        timeAgo: "3 hr ago",
      },
      {
        id: "sa4",
        priority: "low",
        title: "Water intake below target",
        detail: "Encourage one glass with each meal.",
        timeAgo: "1 hr ago",
      },
    ],
  },
  medicines: {
    ramesh: [
      {
        id: "m1",
        name: "Aspirin",
        dosage: "75 mg",
        instruction: "After breakfast with water",
        slot: "morning",
        state: "taken",
        accent: "#3B82F6",
      },
      {
        id: "m2",
        name: "Atorvastatin",
        dosage: "20 mg",
        instruction: "Once daily with breakfast",
        slot: "morning",
        state: "taken",
        accent: "#0D9488",
      },
      {
        id: "m3",
        name: "Clopidogrel",
        dosage: "75 mg",
        instruction: "With evening meal",
        slot: "evening",
        state: "pending",
        accent: "#F59E0B",
      },
      {
        id: "m4",
        name: "Pantoprazole",
        dosage: "40 mg",
        instruction: "Before dinner",
        slot: "evening",
        state: "pending",
        accent: "#64748B",
      },
    ],
    sita: [
      {
        id: "sm1",
        name: "Metformin",
        dosage: "500 mg",
        instruction: "With breakfast",
        slot: "morning",
        state: "missed",
        accent: "#EF4444",
      },
      {
        id: "sm2",
        name: "Amlodipine",
        dosage: "5 mg",
        instruction: "Same time every morning",
        slot: "morning",
        state: "taken",
        accent: "#3B82F6",
      },
      {
        id: "sm3",
        name: "Metformin",
        dosage: "500 mg",
        instruction: "With dinner",
        slot: "evening",
        state: "pending",
        accent: "#F59E0B",
      },
      {
        id: "sm4",
        name: "Vitamin D3",
        dosage: "60k IU",
        instruction: "Weekly · Sunday night",
        slot: "night",
        state: "pending",
        accent: "#0D9488",
      },
    ],
  },
  appointments: {
    ramesh: [
      {
        id: "ap1",
        whenLabel: "Tomorrow",
        countdown: "18 hours left",
        time: "10:30 AM",
        doctorName: "Dr. Ananya Mehta",
        specialty: "Cardiology",
        hospital: "Civil Hospital Ahmedabad",
        address: "Asarwa, Ahmedabad, Gujarat",
        mapQuery: "Civil Hospital Ahmedabad",
      },
    ],
    sita: [
      {
        id: "ap2",
        whenLabel: "Today",
        countdown: "In 3 hours",
        time: "4:30 PM",
        doctorName: "Dr. Ananya Mehta",
        specialty: "Internal Medicine",
        hospital: "Civil Hospital Ahmedabad",
        address: "Asarwa, Ahmedabad, Gujarat",
        mapQuery: "Civil Hospital Ahmedabad",
      },
    ],
  },
  passports: {
    ramesh: {
      name: "Ramesh Patel",
      bloodGroup: "O+",
      allergies: ["None recorded"],
      medicines: ["Aspirin 75 mg", "Atorvastatin 20 mg", "Clopidogrel 75 mg"],
      emergencyContact: "Priya Patel",
      emergencyPhone: "+91 98765 88888",
      qrValue: "HN-RAMESH-PATEL-DEMO",
      abhaId: "12-3456-7890-1101",
    },
    sita: {
      name: "Sita Patel",
      bloodGroup: "B+",
      allergies: ["Penicillin"],
      medicines: ["Metformin 500 mg", "Amlodipine 5 mg"],
      emergencyContact: "Priya Patel",
      emergencyPhone: "+91 98765 88888",
      qrValue: "HN-SITA-PATEL-DEMO",
      abhaId: "12-3456-7890-1102",
    },
  },
  aiInsights: {
    ramesh: {
      summary:
        "Recovery has improved steadily over the last five days. Medicine adherence remains excellent.",
      bullets: [
        "Recommend continuing the current walking and medicine routine.",
        "Complete today's pending sugar check before lunch.",
        "No urgent doctor call is needed unless chest discomfort returns.",
      ],
    },
    sita: {
      summary:
        "Sugar control and one missed medicine need your attention today. BP remains mostly stable.",
      bullets: [
        "Prioritize the 4:30 PM clinic visit and bring today's glucose log.",
        "Set a shared reminder for evening Metformin.",
        "Call the doctor if sugar stays above 180 after dinner.",
      ],
    },
  },
  education: [
    {
      id: "e1",
      category: "today",
      categoryLabel: "Today's Tip",
      title: {
        en: "Sit with them for medicine time",
        hi: "Dawai ke samay unke saath baithiye",
        gu: "Dava na samaye temni sathe beso",
      },
      body: {
        en: "A calm two-minute check-in at morning and evening doses improves adherence more than reminders alone.",
        hi: "Subah aur shaam dawai ke samay do minute saath rehna yaad dilane se behtar kaam karta hai.",
        gu: "Savar ane sanje dava na samaye be minute sathe rahevun yaad apava kartan vadhu asarkarak chhe.",
      },
    },
    {
      id: "e2",
      category: "diet",
      categoryLabel: "Diet Tip",
      title: {
        en: "Pair carbs with protein",
        hi: "Carbs ke saath protein lein",
        gu: "Carbs sathe protein lo",
      },
      body: {
        en: "For Sita, dal or curd with roti helps blunt post-meal sugar spikes.",
        hi: "Sita ke liye roti ke saath dal ya dahi sugar ko sthir rakhne mein madad karta hai.",
        gu: "Sita mate rotli sathe dal athva dahi sugar ne sthir rakhva madad kare chhe.",
      },
    },
    {
      id: "e3",
      category: "exercise",
      categoryLabel: "Exercise Tip",
      title: {
        en: "Short walks beat long gaps",
        hi: "Chhoti sair lambi rukawat se behtar",
        gu: "Tunki walk lamba viram kartan saari",
      },
      body: {
        en: "Ramesh does best with two 10-15 minute walks instead of one long session.",
        hi: "Ramesh ke liye ek lambi sair ki bajay do chhoti sair behtar hai.",
        gu: "Ramesh mate ek lambi walk ne badle be tunki walk vadhu saari chhe.",
      },
    },
    {
      id: "e4",
      category: "emergency",
      categoryLabel: "Emergency Warning",
      title: {
        en: "Know the red flags",
        hi: "Khatre ke sanket jaanein",
        gu: "Jokham na sanketo jano",
      },
      body: {
        en: "Chest pain, sudden breathlessness, confusion, or fainting — call emergency care immediately.",
        hi: "Chhati dard, saans phoolna, bhram ya behoshi — turant aapatkalin madad lein.",
        gu: "Chhati no dukhavo, shwas chadvu, munjvan athva behoshi — tarat katakati sahay lo.",
      },
    },
    {
      id: "e5",
      category: "medicine",
      categoryLabel: "Medicine Tip",
      title: {
        en: "Never double a missed dose",
        hi: "Chhooti dawai dobara na lein",
        gu: "Chhuteli dava bevada na lo",
      },
      body: {
        en: "If a dose was missed more than two hours ago, wait for the next scheduled dose unless the doctor says otherwise.",
        hi: "Yadi dawai do ghante se adhik pehle chhoot gayi ho, to agli nirdharit khurak tak pratiksha karein.",
        gu: "Jo dava be kalak thi vadhu pehla chhuti hoy to aagli niyat matra sudhi raah juo.",
      },
    },
  ],
  activity: {
    ramesh: [
      {
        id: "act1",
        title: "Morning medicines completed",
        detail: "Aspirin and Atorvastatin marked taken",
        timestamp: "8:04 AM",
        tone: "ok",
      },
      {
        id: "act2",
        title: "BP logged",
        detail: "128/82 mmHg recorded by Priya",
        timestamp: "9:02 AM",
        tone: "ok",
      },
      {
        id: "act3",
        title: "Doctor updated care note",
        detail: "Continue current routine · sugar before dinner",
        timestamp: "9:42 AM",
        tone: "info",
      },
      {
        id: "act4",
        title: "Appointment confirmed",
        detail: "Tuesday 10:30 AM · Civil Hospital",
        timestamp: "Yesterday",
        tone: "info",
      },
      {
        id: "act5",
        title: "Passport refreshed",
        detail: "Emergency contacts verified",
        timestamp: "Yesterday",
        tone: "info",
      },
    ],
    sita: [
      {
        id: "sact1",
        title: "Sugar logged high",
        detail: "178 mg/dL before snack",
        timestamp: "10:05 AM",
        tone: "alert",
      },
      {
        id: "sact2",
        title: "Medicine missed",
        detail: "Morning Metformin not confirmed",
        timestamp: "8:45 AM",
        tone: "alert",
      },
      {
        id: "sact3",
        title: "BP logged",
        detail: "134/86 mmHg",
        timestamp: "8:32 AM",
        tone: "ok",
      },
      {
        id: "sact4",
        title: "Doctor flagged sugar trend",
        detail: "Review at 4:30 PM visit",
        timestamp: "8:15 AM",
        tone: "info",
      },
      {
        id: "sact5",
        title: "Care plan shared with you",
        detail: "Hydration and dinner medicine focus",
        timestamp: "Yesterday",
        tone: "info",
      },
    ],
  },
  emergency: {
    doctorPhone: "tel:+917926226464",
    videoLink: "https://meet.google.com/healnexus-care-demo",
    emergencyPhone: "tel:+919876588888",
    hospitalName: "Civil Hospital Ahmedabad",
    hospitalPhone: "tel:+917922680201",
    ambulance: "tel:108",
  },
};
